#[path = "Analysis/analysis.rs"]
pub mod analysis;
#[path = "UI/app.rs"]
pub mod app;
#[path = "Configuration/settings.rs"]
pub mod configuration;
#[path = "Files/file_repository.rs"]
pub mod files;
#[path = "../StlGen/Geometry/mod.rs"]
pub mod generator_geometry;
#[path = "Model/geometry.rs"]
pub mod geometry;
#[path = "Model/mesh.rs"]
pub mod mesh;
#[path = "../StlGen/Output/stl_writers.rs"]
pub mod output;
#[path = "Processing/model_loader.rs"]
pub mod processing;
#[path = "../StlGen/Shapes/samples.rs"]
pub mod samples;
#[path = "../StlGen/Services/benchmark.rs"]
pub mod services;
#[path = "Parsing/stl.rs"]
pub mod stl;
