<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StlGen</RootNamespace>
    <AssemblyName>StlGen</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ParseSTL.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
